/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sun Jul 06 16:42:58 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package net.java.dev.cejug.classifieds.server.contract {

    [Bindable]
    [RemoteClass(alias="net.java.dev.cejug.classifieds.server.contract.AdvertisementRef")]
    public class AdvertisementRef {
        private var _headline:String;
        private var _primaryKey:Number;
        private var _status:Number;

        public function toString():String {
            return headline;
        }

        public function set headline(value:String):void {
            _headline = value;
        }
        public function get headline():String {
            return _headline;
        }

        public function set primaryKey(value:Number):void {
            _primaryKey = value;
        }
        public function get primaryKey():Number {
            return _primaryKey;
        }

        public function set status(value:Number):void {
            _status = value;
        }
        public function get status():Number {
            return _status;
        }
    }
}