/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sun Jul 06 16:43:00 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package net.java.dev.cejug.classifieds.server.contract {

    [Bindable]
    [RemoteClass(alias="net.java.dev.cejug.classifieds.server.contract.CreateDomainParam")]
    public class CreateDomainParam {

        private var _domain:Domain;

        public function set domain(value:Domain):void {
            _domain = value;
        }
        public function get domain():Domain {
            return _domain;
        }

    }
}