/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sun Jul 06 16:42:54 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package net.java.dev.cejug.classifieds.server.contract {

    [Bindable]
    [RemoteClass(alias="net.java.dev.cejug.classifieds.server.contract.CreateCategoryParam")]
    public class CreateCategoryParam {

        private var _advCategory:AdvertisementCategory;

        public function set advCategory(value:AdvertisementCategory):void {
            _advCategory = value;
        }
        public function get advCategory():AdvertisementCategory {
            return _advCategory;
        }

    }
}