/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sun Jul 06 16:42:59 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package net.java.dev.cejug.classifieds.server.contract {

    [Bindable]
    [RemoteClass(alias="net.java.dev.cejug.classifieds.server.contract.Credentials")]
    public class Credentials {

        private var _clientId:String;
        private var _customerId:String;
        private var _customerRole:String;
        private var _group:String;

        public function set clientId(value:String):void {
            _clientId = value;
        }
        public function get clientId():String {
            return _clientId;
        }

        public function set customerId(value:String):void {
            _customerId = value;
        }
        public function get customerId():String {
            return _customerId;
        }

        public function set customerRole(value:String):void {
            _customerRole = value;
        }
        public function get customerRole():String {
            return _customerRole;
        }

        public function set group(value:String):void {
            _group = value;
        }
        public function get group():String {
            return _group;
        }

    }
}