/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sun Jul 06 16:42:54 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package net.java.dev.cejug.classifieds.server.contract {
    import mx.collections.ListCollectionView;
    

    [Bindable]
    [RemoteClass(alias="net.java.dev.cejug.classifieds.server.contract.Domain")]
    public class Domain {

        private var _advCategory:ListCollectionView;
        private var _brand:String;
        private var _uri:String;
        private var _entityId:Number;
        private var _sharedQuota:Boolean;
        private var _timezone:String;

        public function get advCategory():ListCollectionView {
            return _advCategory;
        }
        public function set advCategory(value:ListCollectionView):void {
            _advCategory = value;
        }
        public function set brand(value:String):void {
            _brand = value;
        }
        public function get brand():String {
            return _brand;
        }

        public function set uri(value:String):void {
            _uri = value;
        }
        public function get uri():String {
            return _uri;
        }

        public function set entityId(value:Number):void {
            _entityId = value;
        }
        public function get entityId():Number {
            return _entityId;
        }

        public function set sharedQuota(value:Boolean):void {
            _sharedQuota = value;
        }
        public function get sharedQuota():Boolean {
            return _sharedQuota;
        }

        public function set timezone(value:String):void {
            _timezone = value;
        }
        public function get timezone():String {
            return _timezone;
        }
    }
}