/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sun Jul 06 16:43:00 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package net.java.dev.cejug.classifieds.server.contract {
    import mx.collections.ListCollectionView;
    import javax.xml.datatype.XMLGregorianCalendar;
    

    [Bindable]
    [RemoteClass(alias="net.java.dev.cejug.classifieds.server.contract.MonitorResponse")]
    public class MonitorResponse {

        private var _onlineSince:XMLGregorianCalendar;
        private var _records:ListCollectionView;
        private var _serviceName:String;

        public function set onlineSince(value:XMLGregorianCalendar):void {
            _onlineSince = value;
        }
        public function get onlineSince():XMLGregorianCalendar {
            return _onlineSince;
        }

        public function get records():ListCollectionView {
            return _records;
        }

        public function set serviceName(value:String):void {
            _serviceName = value;
        }
        public function get serviceName():String {
            return _serviceName;
        }
    }
}