/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sun Jul 06 16:43:01 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package net.java.dev.cejug.classifieds.server.contract {
    import javax.xml.datatype.XMLGregorianCalendar;
    
    [Bindable]
    [RemoteClass(alias="net.java.dev.cejug.classifieds.server.contract.OperationTimestamp")]
    public class OperationTimestamp {

        private var _clientId:String;
        private var _finish:XMLGregorianCalendar;
        private var _note:String;
        private var _operationName:String;
        private var _start:XMLGregorianCalendar;
        private var _status:Boolean;

        public function set clientId(value:String):void {
            _clientId = value;
        }
        public function get clientId():String {
            return _clientId;
        }

        public function set finish(value:XMLGregorianCalendar):void {
            _finish = value;
        }
        public function get finish():XMLGregorianCalendar {
            return _finish;
        }

        public function set note(value:String):void {
            _note = value;
        }
        public function get note():String {
            return _note;
        }

        public function set operationName(value:String):void {
            _operationName = value;
        }
        public function get operationName():String {
            return _operationName;
        }

        public function set start(value:XMLGregorianCalendar):void {
            _start = value;
        }
        public function get start():XMLGregorianCalendar {
            return _start;
        }

        public function set status(value:Boolean):void {
            _status = value;
        }
        public function get status():Boolean {
            return _status;
        }
    }
}