/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sun Jul 06 16:43:00 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package net.java.dev.cejug.classifieds.server.contract {

    [Bindable]
    [RemoteClass(alias="net.java.dev.cejug.classifieds.server.contract.Quota")]
    public class Quota {

        private var _advertisementTypeId:int;
        private var _amount:int;
        private var _customerLogin:String;
        private var _domainId:int;

        public function set advertisementTypeId(value:int):void {
            _advertisementTypeId = value;
        }
        public function get advertisementTypeId():int {
            return _advertisementTypeId;
        }

        public function set amount(value:int):void {
            _amount = value;
        }
        public function get amount():int {
            return _amount;
        }

        public function set customerLogin(value:String):void {
            _customerLogin = value;
        }
        public function get customerLogin():String {
            return _customerLogin;
        }

        public function set domainId(value:int):void {
            _domainId = value;
        }
        public function get domainId():int {
            return _domainId;
        }

    }
}