/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sun Jul 06 16:42:59 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package net.java.dev.cejug.classifieds.server.contract {

    [Bindable]
    [RemoteClass(alias="net.java.dev.cejug.classifieds.server.contract.ReadAdvertisementReferencesParam")]
    public class ReadAdvertisementReferencesParam {

        private var _primaryKey:Number;

        public function set primaryKey(value:Number):void {
            _primaryKey = value;
        }
        public function get primaryKey():Number {
            return _primaryKey;
        }
    }
}