/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sun Jul 06 16:42:57 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package net.java.dev.cejug.classifieds.server.contract {

    [Bindable]
    [RemoteClass(alias="net.java.dev.cejug.classifieds.server.contract.ServiceFault")]
    public class ServiceFault {

        private var _code:int;
        private var _details:String;
        private var _headline:String;

        public function set code(value:int):void {
            _code = value;
        }
        public function get code():int {
            return _code;
        }

        public function set details(value:String):void {
            _details = value;
        }
        public function get details():String {
            return _details;
        }

        public function set headline(value:String):void {
            _headline = value;
        }
        public function get headline():String {
            return _headline;
        }

    }
}