/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sun Jul 06 16:42:59 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package net.java.dev.cejug.classifieds.server.contract {

   
    [Bindable]
    [RemoteClass(alias="net.java.dev.cejug.classifieds.server.contract.ServiceStatus")]
    public class ServiceStatus {

        private var _description:String;
        private var _statusCode:int;
        private var _timestamp:Object;

        public function set description(value:String):void {
            _description = value;
        }
        public function get description():String {
            return _description;
        }

        public function set statusCode(value:int):void {
            _statusCode = value;
        }
        public function get statusCode():int {
            return _statusCode;
        }

        public function set timestamp(value:Object):void {
            _timestamp = value;
        }
        public function get timestamp():Object {
            return _timestamp;
        }

    }
}