/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sun Jul 06 16:43:01 CEST 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package net.java.dev.cejug.classifieds.server.contract {
    import mx.collections.ListCollectionView;
    

    [Bindable]
    [RemoteClass(alias="net.java.dev.cejug.classifieds.server.contract.ServiceStatusBundle")]
    public class ServiceStatusBundle {

        private var _serviceStatus:ListCollectionView;

        public function get serviceStatus():ListCollectionView {
            return _serviceStatus;
        }

    }
}